// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package form

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Archived    bool
}
