// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package form

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countForms = `-- name: Count :one
SELECT count(*) FROM forms
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countForms)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const create = `-- name: Create :one
INSERT INTO forms (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at, archived
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Form, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Archived,
	)
	return i, err
}

const deleteForm = `-- name: Delete :execrows
DELETE FROM forms
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsByTitle = `-- name: ExistsByTitle :one
SELECT EXISTS(SELECT 1 FROM forms WHERE title = $1)
`

func (q *Queries) ExistsByTitle(ctx context.Context, title string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByTitle, title)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getByID = `-- name: GetByID :one
SELECT id, title, description, created_at, archived FROM forms
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (Form, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Archived,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, title, description, created_at, archived FROM forms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]Form, error) {
	rows, err := q.db.Query(ctx, list, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []Form{}
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE forms
SET title       = COALESCE($1, title),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, title, description, created_at, archived
`

type UpdateParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	ID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Form, error) {
	row := q.db.QueryRow(ctx, update, arg.Title, arg.Description, arg.ID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Archived,
	)
	return i, err
}
