#!/usr/bin/env bash
# Merges every schema.sql under ./internal into one file for sqlc.
set -e

OUTPUT_FILE="./internal/database/full_schema.sql"

echo -e "-- Code generated by schema merge script. DO NOT EDIT.\n" > "$OUTPUT_FILE"
find ./internal -type f -name "schema.sql" -exec cat {} >> "$OUTPUT_FILE" \;

echo "wrote $OUTPUT_FILE"
